# Generated by Django 4.2.20 on 2025-03-11 09:06

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('raw_file_key', models.CharField(max_length=255, unique=True)),
                ('audio_file_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('transcription_file_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Notification Received'), (1, 'Processing'), (2, 'Processed'), (3, 'Failed'), (4, 'Initialized')], default=4)),
                ('bot_used', models.IntegerField(blank=True, choices=[(0, 'Google'), (1, 'Ms Teams'), (2, 'Zoom')], null=True)),
                ('meeting_timezone', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_meeting_start_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_meeting_end_time', models.DateTimeField(blank=True, null=True)),
                ('execution_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('meeting_ical_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('process_started_at', models.DateTimeField(blank=True, null=True)),
                ('process_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'file_log',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='TranscriptionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('speaker', models.CharField(blank=True, max_length=200, null=True)),
                ('transcription_start_time_milliseconds', models.DurationField(blank=True, null=True)),
                ('transcription_end_time_milliseconds', models.DurationField(blank=True, null=True)),
                ('transcription_Data', models.TextField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('file_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcription_logs', to='transcript_management.filelog')),
            ],
            options={
                'db_table': 'transcription_log',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.AddIndex(
            model_name='filelog',
            index=models.Index(fields=['created_at'], name='file_log_created_0aa2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionlog',
            index=models.Index(fields=['created_at'], name='transcripti_created_9928db_idx'),
        ),
    ]
