# Generated by Django 4.2.20 on 2025-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
