export const ECS_TASK_QUEUE = 'ECS_TASK_QUEUE';
export const ECS_TASK_INITIATE_FAILED_TASK = 'ECS_TASK_INITIATE_FAILED_TASK';

export const OVH_TASK_QUEUE = 'OVH_TASK_QUEUE';
export const OVH_TASK_INITIATE_FAILED_TASK = 'OVH_TASK_INITIATE_FAILED_TASK';
