name: Worker Backend ESLint

on:
  pull_request:
    branches:
      - main
    paths:
      - 'worker-backend/**'

jobs:
  lint:
    name: Run ESLint in Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker-backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run ESLint
        id: lint
        run: |
          docker build --target builder -t worker-backend-lint .
          docker run --rm worker-backend-lint poetry run flake8 . > lint_output.txt 2>&1 || true
          echo "lint_output<<EOF" >> $GITHUB_OUTPUT
          cat lint_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v7
        if: always()
        env:
          LINT_OUTPUT: ${{ steps.lint.outputs.lint_output }}
          JOB_STATUS: ${{ job.status }}
        with:
          script: |
            const output = process.env.LINT_OUTPUT;
            const status = process.env.JOB_STATUS;
            const message = status === 'success' 
              ? '✅ Worker Backend ESLint check passed!'
              : '❌ Worker Backend ESLint check failed. Please fix the issues below:\n\n```\n' + output + '\n```';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            }); 