name: Worker Backend Build Status

on:
  pull_request:
    branches:
      - main
    paths:
      - 'worker-backend/**'

permissions:
  pull-requests: write
  issues: write

jobs:
  build:
    name: Build and Run Worker Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker-backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run
        id: build
        run: |
          docker build -t worker-backend .
          docker run -it worker-backend > build_output.txt 2>&1 || true
          echo "build_output<<EOF" >> $GITHUB_OUTPUT
          cat build_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v7
        if: always()
        env:
          BUILD_OUTPUT: ${{ steps.build.outputs.build_output }}
          JOB_STATUS: ${{ job.status }}
        with:
          script: |
            const output = process.env.BUILD_OUTPUT;
            const status = process.env.JOB_STATUS;
            const message = status === 'success' 
              ? '✅ Worker Backend build check passed!'
              : '❌ Worker Backend build check failed. Please fix the issues below:\n\n```\n' + output + '\n```';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            }); 